# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MyMenu' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    
    use_frameworks!
    
    pod 'AFNetworking'
    pod 'CSStickyHeaderFlowLayout'
    pod 'pop'
    pod 'DZNEmptyDataSet'
    pod 'PINCache'
    pod 'ChameleonFramework'
    pod 'SpinKit'
    pod 'RMPZoomTransitionAnimator'

    # Pods for MyMenu
    
end
