// <auto-generated />
namespace MyMenu.Api.DataEf.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddRestaurant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRestaurant));
        
        string IMigrationMetadata.Id
        {
            get { return "201609022120220_AddRestaurant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
