// <auto-generated />
namespace MyMenu.Api.DataEf.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddDish : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDish));
        
        string IMigrationMetadata.Id
        {
            get { return "201609091747087_AddDish"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
